package roverd

import (
	"errors"
	"fmt"
	"net/url"
	"os"
	"regexp"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

type SerialConfig struct {
	Device string `yaml:"device"`
	Baud   int    `yaml:"baud"`
}

type Duration struct {
	time.Duration
}

func (d *Duration) UnmarshalYAML(value *yaml.Node) error {
	var raw string
	if err := value.Decode(&raw); err != nil {
		return err
	}
	parsed, err := time.ParseDuration(raw)
	if err != nil {
		return err
	}
	d.Duration = parsed
	return nil
}

func (d Duration) MarshalYAML() (interface{}, error) {
	return d.Duration.String(), nil
}

type BRCConfig struct {
	GPIOPin    int      `yaml:"gpioPin"`
	GPIOChip   string   `yaml:"gpioChip"`
	PulseEvery Duration `yaml:"pulseEvery"`
	PulseWidth Duration `yaml:"pulseWidth"`
}

func (b BRCConfig) Enabled() bool {
	return b.GPIOPin >= 0
}

type BatteryConfig struct {
	Full   int `yaml:"full"`
	Warn   int `yaml:"warn"`
	Urgent int `yaml:"urgent"`
}

type AudioConfig struct {
	// AudioConfig is only for sounds generated by roverd itself. Live capture
	// and playback are media-publisher concerns, so those settings live under
	// MediaConfig where they can be written directly into media.env.
	TTSEnabled    bool   `yaml:"ttsEnabled" json:"ttsEnabled"`
	DefaultEngine string `yaml:"defaultEngine" json:"defaultEngine,omitempty"`
	DefaultVoice  string `yaml:"defaultVoice" json:"defaultVoice,omitempty"`
	DefaultPitch  int    `yaml:"defaultPitch" json:"defaultPitch,omitempty"`
}

type HornConfig struct {
	Enabled     bool     `yaml:"enabled" json:"enabled"`
	Volume      float64  `yaml:"volume" json:"-"`
	SampleRate  int      `yaml:"sampleRate" json:"-"`
	Channels    int      `yaml:"channels" json:"-"`
	Device      string   `yaml:"device" json:"-"`
	SineGain    float64  `yaml:"sineGain" json:"-"`
	SawGain     float64  `yaml:"sawGain" json:"-"`
	MaxDuration Duration `yaml:"maxDuration" json:"-"`
}

type MediaConfig struct {
	// PublishPort is shared by the derived video, microphone, and forwarded-audio
	// SRT URLs. Keeping it at this level prevents each nested block from needing
	// to repeat the same server port when the common MediaMTX listener is used.
	PublishPort int `yaml:"publishPort" json:"-"`

	/*
		RTSPPort and WHIPPort do for the low-latency transports what PublishPort does for SRT:
		every stream URL is derived from the server host plus this rover's name, so adding a
		transport does not mean hand-writing three more URLs per rover.

		They are ports rather than full URLs because the stream *names* are not free
		parameters - the server derives the same names independently when it reads these
		streams, so a hand-written URL that disagreed would produce a rover that publishes
		successfully to a path nobody reads. Only the port can differ per deployment.
	*/
	RTSPPort int `yaml:"rtspPort" json:"-"`
	WHIPPort int `yaml:"whipPort" json:"-"`

	Manage         bool                `yaml:"manage" json:"manage"`
	HealthURL      string              `yaml:"healthUrl" json:"healthUrl,omitempty"`
	HealthInterval Duration            `yaml:"healthInterval" json:"-"`
	Video          VideoMediaConfig    `yaml:"video" json:"video"`
	AudioCapture   AudioCaptureConfig  `yaml:"audioCapture" json:"audioCapture"`
	AudioPlayback  AudioPlaybackConfig `yaml:"audioPlayback" json:"audioPlayback"`
}

type VideoMediaConfig struct {
	// Publisher selects the installed publisher script/pipeline family. The
	// first pass uses pi-libcamera for current rovers; laptop-v4l2 can be added
	// without changing the server-facing media shape again.
	Enabled   bool   `yaml:"enabled" json:"enabled"`
	Service   string `yaml:"service" json:"service,omitempty"`
	Publisher string `yaml:"publisher" json:"publisher,omitempty"`
	/*
		Transport selects how encoded frames reach the media server. Measured against a real
		VPS: 39ms over RTSP against 199-235ms over MPEG-TS/SRT. The delay lives in the
		server's mpegts demux, so dropping that container is the whole win and no flag on
		this side can reach it.

		  rtsp    default. Works on ffmpeg 4.x+, needs `rtsp: yes` on the server.
		  whip    27ms and steadier, but the muxer needs ffmpeg >= 7.1 and Pi OS bookworm
		          ships 5.1.
		  mpegts  the previous behaviour. "srt" is an alias.
	*/
	Transport string `yaml:"transport" json:"transport,omitempty"`
	// PublishURL is the MPEG-TS/SRT endpoint and remains the fallback for every rover.
	PublishURL string `yaml:"publishUrl" json:"publishUrl,omitempty"`
	/*
		All three URLs are DERIVED from the server host and this rover's name when left empty -
		see videoStreamName and deriveRTSPURL. Setting one overrides the derivation, which is
		only needed for a non-standard server layout or a one-off test.

		Leaving these empty is the normal case. It does not disable a transport; `transport`
		above is what selects one.
	*/
	RTSPURL     string `yaml:"rtspUrl" json:"rtspUrl,omitempty"`
	WHIPURL     string `yaml:"whipUrl" json:"whipUrl,omitempty"`
	Device      string `yaml:"device" json:"device,omitempty"`
	InputFormat string `yaml:"inputFormat" json:"-"`
	Width       int    `yaml:"width" json:"-"`
	Height      int    `yaml:"height" json:"-"`
	FPS         int    `yaml:"fps" json:"-"`
	Bitrate     int    `yaml:"bitrate" json:"-"`
	Inverted    bool   `yaml:"inverted" json:"-"`
	SensorMode  string `yaml:"sensorMode" json:"-"`
}

type AudioCaptureConfig struct {
	// AudioCapture describes the rover microphone stream that browsers can
	// subscribe to as "<rover>-audio". A disabled capture block still has
	// normalized defaults so enabling it only requires flipping enabled: true.
	Enabled bool   `yaml:"enabled" json:"enabled"`
	Service string `yaml:"service" json:"service,omitempty"`
	// Transport mirrors Video.Transport. The microphone path measured 338ms over MPEG-TS
	// against 181ms over WHIP, the same ~160ms server-side demux cost the video path pays.
	Transport  string `yaml:"transport" json:"transport,omitempty"`
	PublishURL string `yaml:"publishUrl" json:"publishUrl,omitempty"`
	// Derived from the server host and "<rover>-audio" when empty, which is the normal case.
	// RTSP carries an Opus-only stream and works on ffmpeg 4.x+, so it is how a rover on
	// bookworm's ffmpeg 5.1 gets the audio improvement without upgrading ffmpeg.
	RTSPURL    string `yaml:"rtspUrl" json:"rtspUrl,omitempty"`
	WHIPURL    string `yaml:"whipUrl" json:"whipUrl,omitempty"`
	Device     string `yaml:"device" json:"device,omitempty"`
	SampleRate int    `yaml:"sampleRate" json:"-"`
	Channels   int    `yaml:"channels" json:"-"`
	Bitrate    int    `yaml:"bitrate" json:"-"`
}

type AudioPlaybackConfig struct {
	// AudioPlayback describes the reverse stream that VIP users publish into
	// MediaMTX for playback on the rover speaker. The URL is a request/read URL
	// for the rover listener, while the server converts it to publish mode when
	// it needs to inject audio.
	Enabled bool   `yaml:"enabled" json:"enabled"`
	Service string `yaml:"service" json:"service,omitempty"`
	// Transport selects which URL below the rover reads forwarded audio from. Measured on
	// the browser-to-rover path at a matched normalize setting: 138ms over SRT/MPEG-TS
	// against 29.7ms over RTSP, roughly 108ms. The browser already publishes over WHIP, so
	// this read leg is the remaining cost.
	Transport  string `yaml:"transport" json:"transport,omitempty"`
	ForwardURL string `yaml:"forwardUrl" json:"forwardUrl,omitempty"`
	// Derived from the server host and "<rover>-fwd" when empty, which is the normal case.
	// There is no whipUrl here: the rover READS this stream, and WHIP publishes.
	RTSPURL         string `yaml:"rtspUrl" json:"rtspUrl,omitempty"`
	Device          string `yaml:"device" json:"device,omitempty"`
	Normalize       bool   `yaml:"normalize" json:"-"`
	NormalizeFilter string `yaml:"normalizeFilter" json:"-"`
}

type CameraServoConfig struct {
	Enabled       bool    `yaml:"enabled" json:"enabled"`
	Pin           int     `yaml:"pin" json:"pin"`
	FreqHz        int     `yaml:"freqHz" json:"freqHz"`
	CycleLen      int     `yaml:"cycleLen" json:"cycleLen"`
	MinPulseUs    int     `yaml:"minPulseUs" json:"minPulseUs"`
	MaxPulseUs    int     `yaml:"maxPulseUs" json:"maxPulseUs"`
	MinAngle      float64 `yaml:"minAngle" json:"minAngle"`
	MaxAngle      float64 `yaml:"maxAngle" json:"maxAngle"`
	HomeAngle     float64 `yaml:"homeAngle" json:"homeAngle"`
	NudgeDegrees  float64 `yaml:"nudgeDegrees" json:"nudgeDegrees"`
	AllowRawPulse bool    `yaml:"allowRawPulse" json:"allowRawPulse"`
	Invert        bool    `yaml:"invert" json:"invert"`
}

type GPIOToggleConfig struct {
	Enabled   bool   `yaml:"enabled" json:"enabled"`
	GPIOPin   int    `yaml:"gpioPin" json:"gpioPin"`
	GPIOChip  string `yaml:"gpioChip" json:"gpioChip"`
	InitialOn bool   `yaml:"initialOn" json:"initialOn"`
	ActiveLow bool   `yaml:"activeLow" json:"activeLow"`
}

func (g GPIOToggleConfig) LogicalToGPIO(on bool) int {
	// activeLow is the single hardware-inversion point for GPIO toggles. The
	// rest of the daemon, server, and web UI can use normal logical on/off
	// semantics without knowing whether the driver is active-high or active-low.
	if on == g.ActiveLow {
		return 0
	}
	return 1
}

type AutoSideBrushConfig struct {
	Enabled bool `yaml:"enabled"`
	Speed   int  `yaml:"speed"`
}

type PrivateConfig struct {
	Enabled bool                `yaml:"enabled" json:"enabled"`
	Safety  PrivateSafetyConfig `yaml:"safety" json:"safety"`
}

type PrivateSafetyConfig struct {
	SpeedLimitEnabled       bool `yaml:"speedLimitEnabled" json:"speedLimitEnabled"`
	SpeedLimitMaxWheelMMs   int  `yaml:"speedLimitMaxWheelSpeed" json:"speedLimitMaxWheelSpeed"`
	HardOvercurrentEnabled  bool `yaml:"hardOvercurrentEnabled" json:"hardOvercurrentEnabled"`
	OvercurrentStopMs       int  `yaml:"overcurrentStopMs" json:"overcurrentStopMs"`
	HardBumpEnabled         bool `yaml:"hardBumpEnabled" json:"hardBumpEnabled"`
	BumpBackoffSpeed        int  `yaml:"bumpBackoffSpeed" json:"bumpBackoffSpeed"`
	BumpBackoffMs           int  `yaml:"bumpBackoffMs" json:"bumpBackoffMs"`
	CliffEnabled            bool `yaml:"cliffEnabled" json:"cliffEnabled"`
	CliffBackoffSpeed       int  `yaml:"cliffBackoffSpeed" json:"cliffBackoffSpeed"`
	CliffBackoffMs          int  `yaml:"cliffBackoffMs" json:"cliffBackoffMs"`
	VirtualWallEnabled      bool `yaml:"virtualWallEnabled" json:"virtualWallEnabled"`
	VirtualWallBackoffSpeed int  `yaml:"virtualWallBackoffSpeed" json:"virtualWallBackoffSpeed"`
	VirtualWallBackoffMs    int  `yaml:"virtualWallBackoffMs" json:"virtualWallBackoffMs"`
	TriggerCooldownMs       int  `yaml:"triggerCooldownMs" json:"triggerCooldownMs"`
}

type Config struct {
	Name          string              `yaml:"name"`
	Description   string              `yaml:"description" json:"description,omitempty"`
	Color         string              `yaml:"color" json:"color,omitempty"`
	ServerURL     string              `yaml:"serverUrl"`
	Serial        SerialConfig        `yaml:"serial"`
	BRC           BRCConfig           `yaml:"brc"`
	Battery       BatteryConfig       `yaml:"battery"`
	MaxWheelMMs   int                 `yaml:"maxWheelSpeed"`
	Media         MediaConfig         `yaml:"media"`
	CameraServo   CameraServoConfig   `yaml:"cameraServo"`
	Audio         AudioConfig         `yaml:"audio"`
	Horn          HornConfig          `yaml:"horn"`
	Headlight     GPIOToggleConfig    `yaml:"headlight" json:"headlight"`
	Laser         GPIOToggleConfig    `yaml:"laser" json:"laser"`
	AutoSideBrush AutoSideBrushConfig `yaml:"autoSideBrush"`
	Private       PrivateConfig       `yaml:"private" json:"private"`
}

func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	cfg := Config{
		MaxWheelMMs: 500,
		BRC: BRCConfig{
			GPIOPin:  4,
			GPIOChip: "gpiochip0",
			PulseEvery: Duration{
				Duration: time.Minute,
			},
			PulseWidth: Duration{
				Duration: time.Second,
			},
		},
		Media: MediaConfig{
			PublishPort:    9000,
			HealthInterval: Duration{Duration: 30 * time.Second},
			Video: VideoMediaConfig{
				Enabled:    true,
				Service:    "video-publisher.service",
				Publisher:  "pi-libcamera",
				Width:      640,
				Height:     480,
				FPS:        30,
				Bitrate:    2000000,
				Inverted:   true,
				SensorMode: "1296:972",
			},
			AudioCapture: AudioCaptureConfig{
				Enabled:    false,
				Service:    "audio-only-publisher.service",
				Device:     "hw:0,0",
				SampleRate: 48000,
				Channels:   2,
				Bitrate:    510000,
			},
			AudioPlayback: AudioPlaybackConfig{
				Enabled:         true,
				Service:         "audio-forward-listener.service",
				Device:          "forward",
				Normalize:       true,
				NormalizeFilter: "dynaudnorm=f=75:g=15:m=10:p=0.9,alimiter=limit=0.85:level=disabled",
			},
		},
		CameraServo: CameraServoConfig{
			Pin:          12,
			FreqHz:       50,
			CycleLen:     20000,
			MinPulseUs:   900,
			MaxPulseUs:   2100,
			MinAngle:     -15,
			MaxAngle:     30,
			HomeAngle:    0,
			NudgeDegrees: 2,
		},
		Audio: AudioConfig{
			TTSEnabled:    false,
			DefaultEngine: "flite",
			DefaultVoice:  "rms",
			DefaultPitch:  50,
		},
		Horn: HornConfig{
			Enabled:     false,
			Volume:      0.25,
			SampleRate:  48000,
			Channels:    1,
			SineGain:    1.0,
			SawGain:     0.7,
			MaxDuration: Duration{Duration: 10000 * time.Millisecond},
		},
		Headlight: GPIOToggleConfig{
			Enabled:   true,
			GPIOPin:   22,
			GPIOChip:  "gpiochip0",
			InitialOn: false,
			ActiveLow: true,
		},
		Laser: GPIOToggleConfig{
			Enabled:   false,
			GPIOPin:   27,
			GPIOChip:  "gpiochip0",
			InitialOn: false,
			ActiveLow: false,
		},
		AutoSideBrush: AutoSideBrushConfig{
			Enabled: true,
			Speed:   20,
		},
		Private: PrivateConfig{
			Enabled: false,
			Safety: PrivateSafetyConfig{
				SpeedLimitEnabled:       false,
				SpeedLimitMaxWheelMMs:   250,
				HardOvercurrentEnabled:  false,
				OvercurrentStopMs:       300,
				HardBumpEnabled:         false,
				BumpBackoffSpeed:        250,
				BumpBackoffMs:           350,
				CliffEnabled:            false,
				CliffBackoffSpeed:       250,
				CliffBackoffMs:          500,
				VirtualWallEnabled:      true,
				VirtualWallBackoffSpeed: 250,
				VirtualWallBackoffMs:    500,
				TriggerCooldownMs:       800,
			},
		},
	}
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	if cfg.Name == "" {
		return nil, errors.New("missing name")
	}
	normalizedColor, err := normalizeHexColor(cfg.Color)
	if err != nil {
		return nil, err
	}
	cfg.Color = normalizedColor
	if cfg.ServerURL == "" {
		return nil, errors.New("missing serverUrl")
	}
	if cfg.Serial.Device == "" || cfg.Serial.Baud == 0 {
		return nil, errors.New("serial device/baud required")
	}
	if cfg.Battery.Full == 0 {
		return nil, errors.New("battery thresholds required")
	}
	if cfg.MaxWheelMMs <= 0 || cfg.MaxWheelMMs > 500 {
		return nil, fmt.Errorf("maxWheelSpeed must be 1-500, got %d", cfg.MaxWheelMMs)
	}
	if cfg.BRC.GPIOChip == "" {
		cfg.BRC.GPIOChip = "gpiochip0"
	}
	if cfg.Media.PublishPort <= 0 {
		cfg.Media.PublishPort = 9000
	}
	if err := validateMediaConfig(&cfg.Media, cfg.ServerURL, cfg.Name); err != nil {
		return nil, fmt.Errorf("media: %w", err)
	}
	if err := validateServoConfig(&cfg.CameraServo); err != nil {
		return nil, fmt.Errorf("cameraServo: %w", err)
	}
	if err := validateGPIOToggleConfig(&cfg.Headlight); err != nil {
		return nil, fmt.Errorf("headlight: %w", err)
	}
	if err := validateGPIOToggleConfig(&cfg.Laser); err != nil {
		return nil, fmt.Errorf("laser: %w", err)
	}
	validateAudioConfig(&cfg.Audio)
	validateHornConfig(&cfg.Horn)
	validateAutoSideBrushConfig(&cfg.AutoSideBrush)
	return &cfg, nil
}

func validateServoConfig(cfg *CameraServoConfig) error {
	if !cfg.Enabled {
		return nil
	}
	if cfg.Pin <= 0 {
		return errors.New("pin must be > 0")
	}
	if cfg.FreqHz <= 0 {
		return errors.New("freqHz must be > 0")
	}
	if cfg.CycleLen <= 0 {
		return errors.New("cycleLen must be > 0")
	}
	if cfg.MinPulseUs <= 0 || cfg.MaxPulseUs <= 0 {
		return errors.New("minPulseUs/maxPulseUs invalid")
	}
	if cfg.MinPulseUs == cfg.MaxPulseUs {
		return errors.New("minPulseUs/maxPulseUs cannot be equal")
	}
	if cfg.MinPulseUs > cfg.MaxPulseUs {
		cfg.MinPulseUs, cfg.MaxPulseUs = cfg.MaxPulseUs, cfg.MinPulseUs
		cfg.Invert = !cfg.Invert
	}
	if cfg.MinAngle >= cfg.MaxAngle {
		return errors.New("minAngle must be less than maxAngle")
	}
	cfg.HomeAngle = clampFloat(cfg.HomeAngle, cfg.MinAngle, cfg.MaxAngle)
	if cfg.NudgeDegrees <= 0 {
		cfg.NudgeDegrees = 2
	}
	return nil
}

func clampFloat(value, min, max float64) float64 {
	if value < min {
		return min
	}
	if value > max {
		return max
	}
	return value
}

func validateAudioConfig(cfg *AudioConfig) {
	if cfg.DefaultEngine == "" {
		cfg.DefaultEngine = "flite"
	}
	if cfg.DefaultVoice == "" {
		cfg.DefaultVoice = "rms"
	}
	if cfg.DefaultPitch <= 0 {
		cfg.DefaultPitch = 50
	}
}

func validateMediaConfig(cfg *MediaConfig, serverURL string, roverName string) error {
	/*
		The nested media config is the source of truth for the publisher scripts,
		so defaults that used to live in shell are normalized here before any env
		file is written. This keeps the Pi behavior stable while making laptop
		and future publisher variants explicit configuration choices.
	*/
	if cfg.PublishPort <= 0 {
		cfg.PublishPort = 9000
	}
	// MediaMTX's defaults. A deployment using a contiguous port block (see
	// webrtc/deploy/install.sh --port-base) sets these explicitly.
	if cfg.RTSPPort <= 0 {
		cfg.RTSPPort = 8554
	}
	if cfg.WHIPPort <= 0 {
		cfg.WHIPPort = 8889
	}
	if cfg.HealthInterval.Duration <= 0 {
		cfg.HealthInterval = Duration{Duration: 30 * time.Second}
	}
	ports := mediaPorts{srt: cfg.PublishPort, rtsp: cfg.RTSPPort, whip: cfg.WHIPPort}
	if err := validateVideoMediaConfig(&cfg.Video, serverURL, roverName, ports); err != nil {
		return fmt.Errorf("video: %w", err)
	}
	if err := validateAudioCaptureConfig(&cfg.AudioCapture, serverURL, roverName, ports); err != nil {
		return fmt.Errorf("audioCapture: %w", err)
	}
	if err := validateAudioPlaybackConfig(&cfg.AudioPlayback, serverURL, roverName, ports); err != nil {
		return fmt.Errorf("audioPlayback: %w", err)
	}
	return nil
}

// mediaPorts groups the three listener ports so adding a transport does not mean threading
// another positional int through every validator.
type mediaPorts struct {
	srt  int
	rtsp int
	whip int
}

func validateVideoMediaConfig(cfg *VideoMediaConfig, serverURL string, roverName string, ports mediaPorts) error {
	if cfg.Service == "" {
		cfg.Service = "video-publisher.service"
	}
	if cfg.Publisher == "" {
		cfg.Publisher = "pi-libcamera"
	}
	// V4L2 input formats are consumed by ffmpeg as lowercase names such as
	// mjpeg or yuyv422. Normalizing here keeps the publisher script simple and
	// makes hand-edited Debian laptop configs less sensitive to capitalization.
	cfg.InputFormat = strings.ToLower(strings.TrimSpace(cfg.InputFormat))
	if cfg.Width <= 0 {
		cfg.Width = 640
	}
	if cfg.Height <= 0 {
		cfg.Height = 480
	}
	if cfg.FPS <= 0 {
		cfg.FPS = 30
	}
	if cfg.Bitrate <= 0 {
		cfg.Bitrate = 2000000
	}
	if cfg.SensorMode == "" && cfg.Publisher == "pi-libcamera" {
		cfg.SensorMode = "1296:972"
	}
	/*
		Transport defaults to auto, which prefers the lowest-latency option the rover can
		actually use and falls back to MPEG-TS otherwise. An unrecognised value is
		corrected to auto rather than rejected: a typo in this field should not stop a
		rover publishing video, and the publisher logs which transport it selected.
	*/
	cfg.Transport = normalizeMediaTransport(cfg.Transport, "whip", "rtsp", "mpegts", "srt")
	stream := videoStreamName(roverName)
	if cfg.PublishURL == "" {
		derived, err := derivePublishURL(serverURL, stream, ports.srt)
		if err != nil {
			return fmt.Errorf("derive publishUrl: %w", err)
		}
		cfg.PublishURL = derived
	}
	/*
		The low-latency URLs are derived from the rover name exactly as the SRT one is, so a
		rover opts into RTSP or WHIP by naming the transport rather than by pasting URLs.

		An explicitly configured value still wins, which is what makes a non-standard server
		layout or a one-off test possible without changing this code.
	*/
	if cfg.RTSPURL == "" {
		derived, err := deriveRTSPURL(serverURL, stream, ports.rtsp)
		if err != nil {
			return fmt.Errorf("derive rtspUrl: %w", err)
		}
		cfg.RTSPURL = derived
	}
	if cfg.WHIPURL == "" {
		derived, err := deriveWHIPURL(serverURL, stream, ports.whip)
		if err != nil {
			return fmt.Errorf("derive whipUrl: %w", err)
		}
		cfg.WHIPURL = derived
	}
	return nil
}

/*
normalizeMediaTransport resolves the transport field. Absent or unrecognised means "rtsp",
which is the fastest transport every current rover can actually run and needs no extra
configuration, since the URL is derived from the rover's name.

whip is faster still (27ms against 39ms) but its muxer needs ffmpeg >= 7.1 and Raspberry Pi
OS bookworm ships 5.1, so it is opt-in. mpegts restores the previous behaviour.
*/
func normalizeMediaTransport(value string, allowed ...string) string {
	normalized := strings.ToLower(strings.TrimSpace(value))
	for _, candidate := range allowed {
		if normalized == candidate {
			return normalized
		}
	}
	return "rtsp"
}

func validateAudioCaptureConfig(cfg *AudioCaptureConfig, serverURL string, roverName string, ports mediaPorts) error {
	if cfg.Service == "" {
		cfg.Service = "audio-only-publisher.service"
	}
	/*
		This is the rover's MICROPHONE going up to the server, so viewers can hear the room.
		It is a publish, on its own stream name, and is not to be confused with either of the
		other two audio paths - the server sending audio down for the rover's speaker
		(AudioPlayback below), or a driver's browser talking to the rover over WHIP, which
		roverd does not touch at all. See docs/media-transports.md.
	*/
	cfg.Transport = normalizeMediaTransport(cfg.Transport, "whip", "rtsp", "mpegts", "srt")
	if cfg.Device == "" {
		cfg.Device = "hw:0,0"
	}
	if cfg.SampleRate <= 0 {
		cfg.SampleRate = 48000
	}
	if cfg.Channels <= 0 {
		cfg.Channels = 2
	}
	if cfg.Bitrate <= 0 {
		cfg.Bitrate = 510000
	}
	stream := audioCaptureStreamName(roverName)
	if cfg.PublishURL == "" {
		derived, err := derivePublishURL(serverURL, stream, ports.srt)
		if err != nil {
			return fmt.Errorf("derive publishUrl: %w", err)
		}
		cfg.PublishURL = derived
	}
	if cfg.RTSPURL == "" {
		derived, err := deriveRTSPURL(serverURL, stream, ports.rtsp)
		if err != nil {
			return fmt.Errorf("derive rtspUrl: %w", err)
		}
		cfg.RTSPURL = derived
	}
	if cfg.WHIPURL == "" {
		derived, err := deriveWHIPURL(serverURL, stream, ports.whip)
		if err != nil {
			return fmt.Errorf("derive whipUrl: %w", err)
		}
		cfg.WHIPURL = derived
	}
	return nil
}

func validateAudioPlaybackConfig(cfg *AudioPlaybackConfig, serverURL string, roverName string, ports mediaPorts) error {
	/*
		This is the rover's SPEAKER: audio the SERVER produces - TTS, bonk, a VIP upload, or a
		driver's forwarded microphone - which the rover READS and plays locally.

		The direction is why there is no whipUrl here. The rover is a reader on this path, and
		WHIP is a publish protocol; the read-side equivalent would be WHEP, which ffmpeg cannot
		consume. So this path is RTSP or SRT only.
	*/
	cfg.Transport = normalizeMediaTransport(cfg.Transport, "rtsp", "mpegts", "srt")
	if cfg.Service == "" {
		cfg.Service = "audio-forward-listener.service"
	}
	if cfg.Device == "" {
		cfg.Device = "forward"
	}
	if cfg.NormalizeFilter == "" {
		cfg.NormalizeFilter = "dynaudnorm=f=75:g=15:m=10:p=0.9,alimiter=limit=0.85:level=disabled"
	}
	stream := audioForwardStreamName(roverName)
	if cfg.ForwardURL == "" {
		derived, err := deriveReadURL(serverURL, stream, ports.srt)
		if err != nil {
			return fmt.Errorf("derive forwardUrl: %w", err)
		}
		cfg.ForwardURL = derived
	}
	if cfg.RTSPURL == "" {
		derived, err := deriveRTSPURL(serverURL, stream, ports.rtsp)
		if err != nil {
			return fmt.Errorf("derive rtspUrl: %w", err)
		}
		cfg.RTSPURL = derived
	}
	return nil
}

func validateHornConfig(cfg *HornConfig) {
	if cfg.Volume <= 0 {
		cfg.Volume = 0.25
	}
	if cfg.Volume > 1 {
		cfg.Volume = 1
	}
	if cfg.SampleRate <= 0 {
		cfg.SampleRate = 48000
	}
	if cfg.Channels <= 0 {
		cfg.Channels = 1
	}
	if cfg.SineGain <= 0 {
		cfg.SineGain = 1.0
	}
	if cfg.SawGain <= 0 {
		cfg.SawGain = 0.7
	}
	if cfg.MaxDuration.Duration <= 0 {
		cfg.MaxDuration = Duration{Duration: 1200 * time.Millisecond}
	}
}

func validateGPIOToggleConfig(cfg *GPIOToggleConfig) error {
	if !cfg.Enabled {
		return nil
	}
	if cfg.GPIOPin <= 0 {
		return errors.New("gpioPin must be > 0")
	}
	if cfg.GPIOChip == "" {
		cfg.GPIOChip = "gpiochip0"
	}
	return nil
}

func validateAutoSideBrushConfig(cfg *AutoSideBrushConfig) {
	if cfg.Speed == 0 {
		return
	}
	cfg.Speed = clampInt(cfg.Speed, -127, 127)
}

/*
Stream names, derived from the rover's own name.

These three names are the contract between rover and server, and the server derives them
independently from the roster - so they are computed rather than configured. A rover called
"roomba-alpha" publishes video to "roomba-alpha", its microphone to "roomba-alpha-audio",
and reads forwarded audio from "roomba-alpha-fwd", on every transport.

Deriving the name for every transport rather than only SRT is what stops the low-latency
path needing three extra hand-written URLs per rover, and removes the failure mode where a
typo'd URL publishes successfully to a path nothing reads.
*/
func videoStreamName(roverName string) string        { return roverName }
func audioCaptureStreamName(roverName string) string { return roverName + "-audio" }
func audioForwardStreamName(roverName string) string { return roverName + "-fwd" }

func derivePublishURL(serverURL, streamName string, port int) (string, error) {
	return deriveSRTURL(serverURL, streamName, port, "publish")
}

/*
deriveRTSPURL builds the plain RTSP URL for a stream. No transport is stated in the URL:
the publisher pins TCP with -rtsp_transport, because RTSP/UDP has no retransmission and
fails outright across the internet. See webrtc/README.md.
*/
func deriveRTSPURL(serverURL, streamName string, port int) (string, error) {
	host, err := serverHost(serverURL)
	if err != nil {
		return "", err
	}
	if streamName == "" {
		return "", errors.New("missing stream name for rtspUrl")
	}
	if port <= 0 {
		port = 8554
	}
	return fmt.Sprintf("rtsp://%s:%d/%s", host, port, url.PathEscape(streamName)), nil
}

/*
deriveWHIPURL builds the WHIP endpoint. MediaMTX serves WHIP at <path>/whip on its WebRTC
listener, over plain HTTP here for the same reason the rest of this config does: these are
LAN or VPS-internal endpoints and TLS termination is not roverd's concern.
*/
func deriveWHIPURL(serverURL, streamName string, port int) (string, error) {
	host, err := serverHost(serverURL)
	if err != nil {
		return "", err
	}
	if streamName == "" {
		return "", errors.New("missing stream name for whipUrl")
	}
	if port <= 0 {
		port = 8889
	}
	return fmt.Sprintf("http://%s:%d/%s/whip", host, port, url.PathEscape(streamName)), nil
}

func serverHost(serverURL string) (string, error) {
	parsed, err := url.Parse(serverURL)
	if err != nil {
		return "", err
	}
	host := parsed.Hostname()
	if host == "" {
		return "", errors.New("serverUrl missing host")
	}
	return host, nil
}

func deriveReadURL(serverURL, streamName string, port int) (string, error) {
	return deriveSRTURL(serverURL, streamName, port, "request")
}

func deriveSRTURL(serverURL, streamName string, port int, mode string) (string, error) {
	if streamName == "" {
		return "", errors.New("missing stream name for publishUrl")
	}
	if mode == "" {
		mode = "publish"
	}
	parsed, err := url.Parse(serverURL)
	if err != nil {
		return "", err
	}
	host := parsed.Hostname()
	if host == "" {
		return "", errors.New("serverUrl missing host")
	}
	if port <= 0 {
		port = 9000
	}
	escaped := url.PathEscape(streamName)
	return fmt.Sprintf("srt://%s:%d?streamid=#!::r=%s,m=%s&latency=10&mode=caller&transtype=live&pkt_size=1316", host, port, escaped, mode), nil
}

var hexColorRe = regexp.MustCompile(`^#[0-9A-Fa-f]{6}$`)

func normalizeHexColor(raw string) (string, error) {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return "", nil
	}
	if !hexColorRe.MatchString(trimmed) {
		return "", fmt.Errorf("color must be #RRGGBB, got %q", raw)
	}
	return strings.ToUpper(trimmed), nil
}
